/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Diff: typeof import('./components/dataSources/GitAgent/Diff.vue')['default']
    File: typeof import('./components/dataSources/GitAgent/File.vue')['default']
    GitLab: typeof import('./components/dataSources/GitLab.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Main: typeof import('./components/dataSources/GitAgent/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
